# Generated by Django 4.2.5 on 2023-10-02 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0005_rename_tenant_foodcategory_resturent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant', '0006_delete_resturentawaremodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_number', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=20)),
                ('item_name', models.CharField(max_length=20)),
                ('item_price', models.CharField(max_length=20)),
                ('item_description', models.CharField(max_length=20)),
                ('order_type', models.CharField(max_length=20)),
                ('table', models.CharField(max_length=20)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='management.fooditem')),
                ('resturent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.resturent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InHouseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=20)),
                ('total_price', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('orders', models.ManyToManyField(related_name='inhouseorder', to='orderandbilling.order')),
                ('resturent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.resturent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('orders', models.ManyToManyField(related_name='order_delivery', to='orderandbilling.order')),
                ('resturent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.resturent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_delivery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
