# Generated by Django 4.2.5 on 2023-10-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableandspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableandspace',
            name='status',
            field=models.CharField(choices=[('AV', 'Available'), ('OC', 'Occupied'), ('RE', 'Reserved')], default='AV', max_length=2),
        ),
    ]
