# Generated by Django 4.2.5 on 2023-10-02 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_delete_resturentawaremodel'),
        ('tableandspace', '0002_alter_tableandspace_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableandspace',
            name='resturent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenant.resturent'),
            preserve_default=False,
        ),
    ]
