# Generated by Django 4.2.5 on 2023-10-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableandspace', '0002_alter_tableandspace_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableandspace',
            name='category',
            field=models.CharField(choices=[('SA', 'Sofa'), ('SP', 'Space'), ('BO', 'Booth'), ('BA', 'Bar'), ('OU', 'Outdoor'), ('PR', 'Private')], default='SP', max_length=20),
        ),
    ]
