# Generated by Django 4.2.5 on 2023-10-01 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_remove_client_created_on_remove_client_on_trial_and_more'),
        ('account', '0002_customuser_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='tenant.client'),
        ),
    ]
