# Generated by Django 4.2.5 on 2023-10-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='name_md',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
