# Generated by Django 4.2.5 on 2023-10-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='food_item',
            field=models.ManyToManyField(blank=True, related_name='food_category', to='management.fooditem'),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='food_item',
            field=models.ManyToManyField(blank=True, related_name='menu_category', to='management.fooditem'),
        ),
    ]
