# Generated by Django 4.2.5 on 2023-10-08 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_fooditem_name_md'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='name_md',
        ),
    ]
