# Generated by Django 4.2.5 on 2023-10-02 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_delete_resturentawaremodel'),
        ('management', '0003_foodcategory_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenant.resturent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menucategory',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenant.resturent'),
            preserve_default=False,
        ),
    ]
