# Generated by Django 4.2.5 on 2023-10-02 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_fooditem_tenant_menucategory_tenant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodcategory',
            old_name='tenant',
            new_name='resturent',
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='tenant',
            new_name='resturent',
        ),
        migrations.RenameField(
            model_name='menucategory',
            old_name='tenant',
            new_name='resturent',
        ),
    ]
