# Generated by Django 4.2.5 on 2023-10-02 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('tenant', '0002_remove_client_created_on_remove_client_on_trial_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Resturent',
        ),
        migrations.RenameModel(
            old_name='Domain',
            new_name='ResturentAwareModel',
        ),
    ]
