# Generated by Django 4.2.5 on 2023-10-02 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_rename_client_resturent_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResturentAwareModel',
            new_name='ResturentTenantAwareModel',
        ),
    ]
