# Generated by Django 4.2.5 on 2023-10-02 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_rename_resturentawaremodel_resturenttenantawaremodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResturentAwareModel',
            fields=[
                ('resturent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tenant.resturent')),
            ],
            options={
                'abstract': False,
            },
            bases=('tenant.resturent',),
        ),
    ]
